// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OTPService is an autogenerated mock type for the OTPService type
type OTPService struct {
	mock.Mock
}

// GenerateOTP provides a mock function with given fields:
func (_m *OTPService) GenerateOTP() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// UseOTP provides a mock function with given fields: otpToUse
func (_m *OTPService) UseOTP(otpToUse string) error {
	ret := _m.Called(otpToUse)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(otpToUse)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
