// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/MrKAKTyC/lets-go-chat/pkg/config"
	"github.com/MrKAKTyC/lets-go-chat/pkg/controller"
	"github.com/MrKAKTyC/lets-go-chat/pkg/repository"
	"github.com/MrKAKTyC/lets-go-chat/pkg/server/websocket"
	"github.com/MrKAKTyC/lets-go-chat/pkg/service"
)

// Injectors from wire.go:

func InitializeController(co config.Config) *controller.User {
	dbConfig := co.DB
	db := repository.GetDBConnection(dbConfig)
	userRepository := repository.NewUserPGS(db)
	otpStorage := repository.NewInMemoryOTP()
	otpService := service.NewOtp(otpStorage)
	userService := service.NewUser(userRepository, otpService)
	messageRepository := repository.NewMessagePGS(db)
	room := websocket.NewChatRoom(otpService, messageRepository, userRepository)
	user := controller.NewUser(userService, room)
	return user
}
